"""add cat column again

Revision ID: 088023a18f8d
Revises: aeb1c47a5817
Create Date: 2025-08-27 19:22:27.912579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088023a18f8d'
down_revision = 'aeb1c47a5817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('cat')

    # ### end Alembic commands ###
