"""add editor

Revision ID: c27c1a6fcbad
Revises: eaa9201f2486
Create Date: 2025-08-14 22:03:44.195955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27c1a6fcbad'
down_revision = 'eaa9201f2486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor', sa.String(length=50), nullable=True))
        batch_op.drop_column('file_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_key', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('editor')

    # ### end Alembic commands ###
